import type { AuditLogRecord } from '@/types/audit-log'

/**
 * 审核员控制台兜底示例数据（原型 docs/mockups/原型展示-审核员v1.1_待评审20260917.html globalLogs 扩展）。
 * 字段与取值全部按后端真实契约书写：action/old_status/new_status 用枚举码，中文经字典渲染。
 *
 * entity_type 按后端实际写入规则区分（docs/api-spec.md 第 3/4/5 节）：
 * - 准入审核 → SUPPLIER（entity_id=供应商 ID）
 * - 停用/恢复/淘汰终审 → LIFECYCLE_REQUEST（entity_id=申请单 ID，状态流转是申请单的 PENDING→APPROVED）
 * - 绩效复核 → PERFORMANCE_EVALUATION（entity_id=评价单 ID）
 * 因此"按供应商聚合追溯日志"无法只靠 entity_id 实现，需后端补 supplier_id 维度查询；
 * 兜底模式下子组件按 entity_name 匹配，保证三类记录都能展示。
 */
export const REVIEW_LOG_DEMO_LIST: AuditLogRecord[] = [
  {
    id: 1,
    entity_type: 'SUPPLIER',
    entity_id: 2,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'AUDIT_REJECT',
    old_status: 'PENDING_REVIEW',
    new_status: 'RETURNED',
    result: 'REJECTED',
    comment: '营业执照扫描件模糊不清，税号与工商信息不匹配，退回业务员修正',
    created_at: '2026-09-16T09:30:00',
    entity_name: '上海华联部件有限公司',
  },
  {
    id: 2,
    entity_type: 'SUPPLIER',
    entity_id: 3,
    operator_id: 3,
    operator_name: 'Auditor_01',
    operator_role: 'AUDITOR',
    action: 'AUDIT_APPROVE',
    old_status: 'PENDING_REVIEW',
    new_status: 'NORMAL',
    result: 'SUCCESS',
    comment: '营业执照核验无误，批准准入',
    created_at: '2026-09-16T10:15:20',
    entity_name: '深圳迅捷物流有限公司',
  },
  {
    id: 3,
    entity_type: 'SUPPLIER',
    entity_id: 1,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'AUDIT_APPROVE',
    old_status: 'PENDING_REVIEW',
    new_status: 'NORMAL',
    result: 'SUCCESS',
    comment: '资质齐全，签署准予入驻',
    created_at: '2026-09-16T11:05:00',
    entity_name: '北京智造科技有限公司',
  },
  {
    id: 4,
    entity_type: 'LIFECYCLE_REQUEST',
    entity_id: 101,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'DECISION_APPROVE',
    old_status: 'PENDING',
    new_status: 'APPROVED',
    result: 'SUCCESS',
    comment: '同意业务员申请：供货质量连续两次抽检不合格，供应商置为 SUSPENDED',
    created_at: '2026-09-17T09:40:12',
    entity_name: '广州宏达电子有限公司',
  },
  {
    id: 5,
    entity_type: 'LIFECYCLE_REQUEST',
    entity_id: 102,
    operator_id: 3,
    operator_name: 'Auditor_01',
    operator_role: 'AUDITOR',
    action: 'DECISION_APPROVE',
    old_status: 'PENDING',
    new_status: 'APPROVED',
    result: 'SUCCESS',
    comment: '整改验收合格，批准恢复合作，供应商置为 NORMAL',
    created_at: '2026-09-17T15:20:35',
    entity_name: '天津重工机械厂',
  },
  {
    id: 6,
    entity_type: 'PERFORMANCE_EVALUATION',
    entity_id: 201,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'REVIEW_APPROVE',
    old_status: 'PENDING_REVIEW',
    new_status: 'APPROVED',
    result: 'SUCCESS',
    comment: '复核结论：通过该季度评分（87.25 分，B 级）',
    created_at: '2026-09-18T10:12:48',
    entity_name: '深圳迅捷物流有限公司',
  },
  {
    id: 7,
    entity_type: 'SUPPLIER',
    entity_id: 2,
    operator_id: 3,
    operator_name: 'Auditor_01',
    operator_role: 'AUDITOR',
    action: 'AUDIT_APPROVE',
    old_status: 'PENDING_REVIEW',
    new_status: 'NORMAL',
    result: 'SUCCESS',
    comment: '补充联系邮箱后重新送审，核验通过准予入驻',
    created_at: '2026-09-18T16:02:30',
    entity_name: '上海华联部件有限公司',
  },
  {
    id: 8,
    entity_type: 'LIFECYCLE_REQUEST',
    entity_id: 103,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'DECISION_REJECT',
    old_status: 'PENDING',
    new_status: 'REJECTED',
    result: 'REJECTED',
    comment: '整改证据不足，驳回淘汰申请，供应商维持 SUSPENDED',
    created_at: '2026-09-19T09:05:10',
    entity_name: '沧州重工机械配件厂',
  },
]
