import type { ReviewLogItem } from '@/types/audit-log'

/**
 * 原型示例日志数据（docs/mockups/原型展示-审核员v1.1_待评审20260917.html globalLogs 扩展，
 * 覆盖全部审核动作类型；supplier_id 与审核员控制台演示供应商一一对应）。
 * 后端日志扩展筛选接口就绪前，供全量审批日志表格与追溯日志子组件兜底演示用。
 */
export const REVIEW_LOG_DEMO_LIST: ReviewLogItem[] = [
  {
    id: 1,
    created_at: '2026-09-16 09:30:00',
    supplier_id: 2,
    supplier_name: '上海华联部件有限公司',
    operator_name: 'Yangwei (业务员)',
    action_type: '资质审核驳回',
    old_status: '待审核',
    new_status: '待修改',
    comment: '营业执照扫描件模糊不清，税号与工商信息不匹配，退回业务员修正',
  },
  {
    id: 2,
    created_at: '2026-09-16 10:15:20',
    supplier_id: 3,
    supplier_name: '深圳迅捷物流有限公司',
    operator_name: 'Auditor_01 (审计员)',
    action_type: '资质审核通过',
    old_status: '待审核',
    new_status: '正常/合作中',
    comment: '营业执照核验无误，批准准入',
  },
  {
    id: 3,
    created_at: '2026-09-16 11:05:00',
    supplier_id: 1,
    supplier_name: '北京智造科技有限公司',
    operator_name: 'LiSi (审核员)',
    action_type: '资质审核通过',
    old_status: '待审核',
    new_status: '正常/合作中',
    comment: '资质齐全，签署准予入驻',
  },
  {
    id: 4,
    created_at: '2026-09-17 09:40:12',
    supplier_id: 7,
    supplier_name: '广州宏达电子有限公司',
    operator_name: 'LiSi (审核员)',
    action_type: '批准停用',
    old_status: '正常/合作中',
    new_status: '停用',
    comment: '同意业务员申请：供货质量连续两次抽检不合格，暂停合作',
  },
  {
    id: 5,
    created_at: '2026-09-17 15:20:35',
    supplier_id: 8,
    supplier_name: '天津重工机械厂',
    operator_name: 'Auditor_01 (审计员)',
    action_type: '恢复正常合作',
    old_status: '停用',
    new_status: '正常/合作中',
    comment: '审计员决策解除停用限制，恢复正常合作状态',
  },
  {
    id: 6,
    created_at: '2026-09-18 10:12:48',
    supplier_id: 3,
    supplier_name: '深圳迅捷物流有限公司',
    operator_name: 'LiSi (审核员)',
    action_type: '绩效复核通过',
    old_status: '待审计员复核',
    new_status: '已复核通过',
    comment: '复核结论：通过该季度评分（87.25分，B级）',
  },
  {
    id: 7,
    created_at: '2026-09-18 16:02:30',
    supplier_id: 2,
    supplier_name: '上海华联部件有限公司',
    operator_name: 'Auditor_01 (审计员)',
    action_type: '资质审核通过',
    old_status: '待审核',
    new_status: '正常/合作中',
    comment: '补充联系邮箱后重新送审，核验通过准予入驻',
  },
  {
    id: 8,
    created_at: '2026-09-19 09:05:10',
    supplier_id: 6,
    supplier_name: '沧州重工机械配件厂',
    operator_name: 'LiSi (审核员)',
    action_type: '批准淘汰',
    old_status: '停用',
    new_status: '淘汰',
    comment: '整改期满仍未达恢复标准，终审批准退出合作',
  },
]
