import type { AuditLogRecord } from '@/types/audit-log'

/**
 * 业务员控制台兜底示例数据（原型 docs/mockups/原型展示-采购员v1.1_待评审20260929.html globalLogs 改造）。
 * action / old_status / new_status 全部使用后端枚举码，中文由 @/constants/auditDictionary 渲染。
 *
 * 注意：后端 AuditAction 现有 11 个码 = 业务域 SUBMIT / AUDIT_* / REVIEW_* / DECISION_* 七码，
 * 加用户域 CREATE_USER / UPDATE_USER / ENABLE_USER / DISABLE_USER 四码（entity_type=USER，仅 ADMIN 触发）；
 * 用户域四码不属业务员视角，供应商日志里仍只会出现业务域码，故本示例数据无需增删。
 * 原型业务员的"新增档案 / 修改档案 / 逻辑删除草稿 / 申请变更状态 / 申请恢复合作"无对应码值，
 * 故本示例只保留能用真实码表达的记录（供应商建档送审=SUBMIT + SUPPLIER 对象，
 * 一步式绩效事实提交=SUBMIT + PERFORMANCE_EVALUATION 对象，草稿对象类型已废弃）；
 * 待后端补充 CRUD 动作码后再扩充，前端不自造码。
 */
export const SUPPLIER_LOG_DEMO_LIST: AuditLogRecord[] = [
  {
    id: 1,
    entity_type: 'SUPPLIER',
    entity_id: 1,
    operator_id: 2,
    operator_name: '杨伟',
    operator_role: 'STAFF',
    action: 'SUBMIT',
    old_status: 'DRAFT',
    new_status: 'PENDING_REVIEW',
    result: 'SUCCESS',
    comment: '完成初始信息录入与营业执照挂载，提交资质送审',
    created_at: '2026-09-16T09:15:20',
    entity_name: '北京智造科技有限公司',
  },
  {
    id: 2,
    entity_type: 'SUPPLIER',
    entity_id: 2,
    operator_id: 2,
    operator_name: '杨伟',
    operator_role: 'STAFF',
    action: 'SUBMIT',
    old_status: 'DRAFT',
    new_status: 'PENDING_REVIEW',
    result: 'SUCCESS',
    comment: '提交资质文件送审计员审核',
    created_at: '2026-09-16T09:30:10',
    entity_name: '上海华联部件有限公司',
  },
  {
    id: 3,
    entity_type: 'SUPPLIER',
    entity_id: 2,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'AUDIT_REJECT',
    old_status: 'PENDING_REVIEW',
    new_status: 'RETURNED',
    result: 'REJECTED',
    comment: '联系邮箱缺失，退回业务员修正',
    created_at: '2026-09-16T11:20:05',
    entity_name: '上海华联部件有限公司',
  },
  {
    id: 4,
    entity_type: 'SUPPLIER',
    entity_id: 2,
    operator_id: 2,
    operator_name: '杨伟',
    operator_role: 'STAFF',
    action: 'SUBMIT',
    old_status: 'RETURNED',
    new_status: 'PENDING_REVIEW',
    result: 'SUCCESS',
    comment: '按审批意见补充联系邮箱后重新提交准入',
    created_at: '2026-09-16T14:05:33',
    entity_name: '上海华联部件有限公司',
  },
  {
    id: 5,
    entity_type: 'SUPPLIER',
    entity_id: 3,
    operator_id: 3,
    operator_name: 'Auditor_01',
    operator_role: 'AUDITOR',
    action: 'AUDIT_APPROVE',
    old_status: 'PENDING_REVIEW',
    new_status: 'NORMAL',
    result: 'SUCCESS',
    comment: '资质齐全，同意成为合格供应商',
    created_at: '2026-09-16T10:10:00',
    entity_name: '深圳迅捷物流有限公司',
  },
  {
    id: 6,
    entity_type: 'PERFORMANCE_EVALUATION',
    entity_id: 301,
    operator_id: 2,
    operator_name: '杨伟',
    operator_role: 'STAFF',
    action: 'SUBMIT',
    old_status: null,
    new_status: 'PENDING_REVIEW',
    result: 'SUCCESS',
    comment: '提交 2026 年 Q3 客观履约事实数据，算分与评级由后端引擎计算',
    created_at: '2026-09-18T16:35:27',
    entity_name: '深圳迅捷物流有限公司',
  },
  {
    id: 7,
    entity_type: 'SUPPLIER',
    entity_id: 4,
    operator_id: 2,
    operator_name: '杨伟',
    operator_role: 'STAFF',
    action: 'SUBMIT',
    old_status: 'DRAFT',
    new_status: 'PENDING_REVIEW',
    result: 'SUCCESS',
    comment: '新供应商建档并提交准入审核',
    created_at: '2026-09-17T09:20:48',
    entity_name: '沧州重工机械配件厂',
  },
  {
    id: 8,
    entity_type: 'LIFECYCLE_REQUEST',
    entity_id: 103,
    operator_id: 3,
    operator_name: '李四',
    operator_role: 'AUDITOR',
    action: 'DECISION_REJECT',
    old_status: 'PENDING',
    new_status: 'REJECTED',
    result: 'REJECTED',
    comment: '整改证据不足，驳回淘汰申请，供应商维持停用',
    created_at: '2026-09-19T09:05:10',
    entity_name: '沧州重工机械配件厂',
  },
]
