import type { SupplierLogItem } from '@/types/supplier-log'

/**
 * 原型示例日志数据（docs/mockups/原型展示-采购员v1.1_待评审20260929.html globalLogs 扩展）。
 * 后端日志扩展筛选接口就绪前，供全量日志表格与档案追溯日志子组件兜底演示用。
 */
export const SUPPLIER_LOG_DEMO_LIST: SupplierLogItem[] = [
  {
    id: 1,
    created_at: '2026-09-16 09:15:20',
    supplier_id: 1,
    supplier_name: '北京智造科技有限公司',
    operator_name: 'Yangwei (业务员)',
    action_type: '新增档案',
    old_status: '无',
    new_status: '草稿/待提交',
    comment: '完成初始信息录入与营业执照挂载',
  },
  {
    id: 2,
    created_at: '2026-09-16 09:30:10',
    supplier_id: 2,
    supplier_name: '上海华联部件有限公司',
    operator_name: 'Yangwei (业务员)',
    action_type: '提交准入',
    old_status: '草稿/待提交',
    new_status: '待审核',
    comment: '提交资质文件送审计员审核',
  },
  {
    id: 3,
    created_at: '2026-09-16 10:10:00',
    supplier_id: 3,
    supplier_name: '深圳迅捷物流有限公司',
    operator_name: 'Auditor_01 (审计员)',
    action_type: '提交准入',
    old_status: '待审核',
    new_status: '正常/合作中',
    comment: '资质齐全，同意成为合格供应商',
  },
  {
    id: 4,
    created_at: '2026-09-16 14:05:33',
    supplier_id: 2,
    supplier_name: '上海华联部件有限公司',
    operator_name: 'Yangwei (业务员)',
    action_type: '修改档案',
    old_status: '待修改',
    new_status: '待审核',
    comment: '按审批意见补充联系邮箱后重新提交准入',
  },
  {
    id: 5,
    created_at: '2026-09-17 09:20:48',
    supplier_id: 5,
    supplier_name: '苏州精密零配件厂',
    operator_name: 'Yangwei (业务员)',
    action_type: '逻辑删除草稿',
    old_status: '草稿/待提交',
    new_status: '草稿/待提交',
    comment: '重复建档，删除本人草稿档案（逻辑删除）',
  },
  {
    id: 6,
    created_at: '2026-09-17 15:40:12',
    supplier_id: 4,
    supplier_name: '沧州重工机械配件厂',
    operator_name: 'Yangwei (业务员)',
    action_type: '申请变更状态',
    old_status: '正常/合作中',
    new_status: '正常/合作中',
    comment: '提交停用申请（D级绩效依据），已送 AUDITOR 终审',
  },
  {
    id: 7,
    created_at: '2026-09-18 10:02:55',
    supplier_id: 4,
    supplier_name: '沧州重工机械配件厂',
    operator_name: 'Yangwei (业务员)',
    action_type: '申请恢复合作',
    old_status: '停用',
    new_status: '停用',
    comment: '整改完成，提交恢复合作申请，待审计员终审',
  },
  {
    id: 8,
    created_at: '2026-09-18 16:35:27',
    supplier_id: 3,
    supplier_name: '深圳迅捷物流有限公司',
    operator_name: 'Yangwei (业务员)',
    action_type: '绩效客观事实录入',
    old_status: '正常/合作中',
    new_status: '正常/合作中',
    comment: '提交2026年 Q3客观事实数据，后端算分得分: 88.5分 (B级)',
  },
]
