name: Qoder Assistant

on:
  issue_comment:
    types: [created]

jobs:
  assistant:
    runs-on: ubuntu-latest

    steps:
      - uses: QoderAI/qoder-action@v0
        with:
          qoder_personal_access_token: ${{ secrets.QODER_PERSONAL_ACCESS_TOKEN }}
          prompt: |
            /assistant
